# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: healthchecksio
version: 0.1.0
readme: README.md
authors:
  - Mark Mercado (https://github.com/mamercad)
description: Healthchecks.io Ansible Collection
license_file: LICENSE
tags:
  - healthchecks
  - healthchecks.io
repository: https://github.com/mamercad/community.healthchecksio
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/mamercad/community.healthchecksio
issues: https://github.com/mamercad/community.healthchecksio/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
